sandbox__data_modelling:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1
  target: dev

macro_test:
  outputs:
    test:
      type: duckdb
      path: test.duckdb
      threads: 1
  target: test
